// src/services/room.service.js
// CodeArena — Room Service (Phase 2)

import { supabaseAdmin } from '../config/supabase.js';

// ─────────────────────────────────────────────
// Create Room
// ─────────────────────────────────────────────
export async function createRoom(hostId, options) {
  const {
    name,
    duration_mins = 60,
    max_members = 10,
    is_private = true,
    difficulty = [],
    topics = [],
    allow_language = ['javascript', 'python', 'cpp', 'java'],
    show_leaderboard = true,
  } = options;

  const { data, error } = await supabaseAdmin
    .from('rooms')
    .insert({
      name,
      host_id: hostId,
      duration_mins,
      max_members,
      is_private,
      difficulty,
      topics,
      allow_language,
      show_leaderboard,
      // code is auto-generated by DB trigger
    })
    .select(`
      *,
      host:users!rooms_host_id_fkey (id, username, display_name, avatar_url)
    `)
    .single();

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return data;
}

// ─────────────────────────────────────────────
// Get Room by ID (with members)
// ─────────────────────────────────────────────
export async function getRoomById(roomId, requestingUserId) {
  const { data: room, error } = await supabaseAdmin
    .from('rooms')
    .select(`
      *,
      host:users!rooms_host_id_fkey (id, username, display_name, avatar_url),
      room_members (
        id,
        role,
        is_ready,
        joined_at,
        user:users (id, username, display_name, avatar_url)
      )
    `)
    .eq('id', roomId)
    .single();

  if (error || !room) throw Object.assign(new Error('Room not found'), { code: 'NOT_FOUND', status: 404 });

  // Private room — only members can view
  if (room.is_private) {
    const isMember = room.room_members.some(m => m.user.id === requestingUserId);
    if (!isMember) throw Object.assign(new Error('Access denied'), { code: 'FORBIDDEN', status: 403 });
  }

  return room;
}

// ─────────────────────────────────────────────
// Get Room by Code
// ─────────────────────────────────────────────
export async function getRoomByCode(code) {
  const { data, error } = await supabaseAdmin
    .from('rooms')
    .select(`
      id, code, name, status, is_private, max_members, duration_mins,
      difficulty, topics, allow_language, show_leaderboard, created_at,
      host:users!rooms_host_id_fkey (id, username, display_name, avatar_url),
      room_members (id)
    `)
    .eq('code', code.toUpperCase())
    .single();

  if (error || !data) throw Object.assign(new Error('Room not found — check the code and try again'), { code: 'NOT_FOUND', status: 404 });
  return data;
}

// ─────────────────────────────────────────────
// Join Room
// ─────────────────────────────────────────────
export async function joinRoom(userId, code) {
  const room = await getRoomByCode(code);

  // Status checks
  if (room.status === 'active') {
    throw Object.assign(new Error('This room is already in progress'), { code: 'ROOM_ACTIVE', status: 409 });
  }
  if (room.status === 'completed' || room.status === 'cancelled') {
    throw Object.assign(new Error('This room has ended'), { code: 'ROOM_ENDED', status: 409 });
  }

  // Capacity check
  const currentCount = room.room_members.length;
  if (currentCount >= room.max_members) {
    throw Object.assign(new Error('Room is full'), { code: 'ROOM_FULL', status: 409 });
  }

  // Already a member?
  const { data: existing } = await supabaseAdmin
    .from('room_members')
    .select('id')
    .eq('room_id', room.id)
    .eq('user_id', userId)
    .single();

  if (existing) {
    // Already in — just return the room
    return getRoomById(room.id, userId);
  }

  // Insert member
  const { error } = await supabaseAdmin
    .from('room_members')
    .insert({ room_id: room.id, user_id: userId, role: 'participant' });

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });

  return getRoomById(room.id, userId);
}

// ─────────────────────────────────────────────
// Leave Room
// ─────────────────────────────────────────────
export async function leaveRoom(userId, roomId) {
  const room = await getRoomById(roomId, userId);

  if (room.host_id === userId) {
    throw Object.assign(new Error('Host cannot leave — transfer host or cancel the room'), { code: 'HOST_CANNOT_LEAVE', status: 400 });
  }

  const { error } = await supabaseAdmin
    .from('room_members')
    .delete()
    .eq('room_id', roomId)
    .eq('user_id', userId);

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return { message: 'Left room successfully' };
}

// ─────────────────────────────────────────────
// Set Ready Status
// ─────────────────────────────────────────────
export async function setReady(userId, roomId, isReady) {
  const { error } = await supabaseAdmin
    .from('room_members')
    .update({ is_ready: isReady })
    .eq('room_id', roomId)
    .eq('user_id', userId);

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return { is_ready: isReady };
}

// ─────────────────────────────────────────────
// Start Room (host only)
// ─────────────────────────────────────────────
export async function startRoom(hostId, roomId) {
  const room = await getRoomById(roomId, hostId);

  if (room.host_id !== hostId) {
    throw Object.assign(new Error('Only the host can start the room'), { code: 'FORBIDDEN', status: 403 });
  }
  if (room.status !== 'waiting') {
    throw Object.assign(new Error(`Room is already ${room.status}`), { code: 'INVALID_STATUS', status: 409 });
  }
  if (room.room_members.length < 1) {
    throw Object.assign(new Error('Need at least 1 member to start'), { code: 'NOT_ENOUGH_MEMBERS', status: 400 });
  }

  const startsAt = new Date();
  const endsAt   = new Date(startsAt.getTime() + room.duration_mins * 60 * 1000);

  const { data, error } = await supabaseAdmin
    .from('rooms')
    .update({ status: 'active', starts_at: startsAt, ends_at: endsAt })
    .eq('id', roomId)
    .select()
    .single();

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return data;
}

// ─────────────────────────────────────────────
// Cancel Room (host only)
// ─────────────────────────────────────────────
export async function cancelRoom(hostId, roomId) {
  const room = await getRoomById(roomId, hostId);

  if (room.host_id !== hostId) {
    throw Object.assign(new Error('Only the host can cancel the room'), { code: 'FORBIDDEN', status: 403 });
  }
  if (room.status === 'completed' || room.status === 'cancelled') {
    throw Object.assign(new Error(`Room is already ${room.status}`), { code: 'INVALID_STATUS', status: 409 });
  }

  const { data, error } = await supabaseAdmin
    .from('rooms')
    .update({ status: 'cancelled' })
    .eq('id', roomId)
    .select()
    .single();

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return data;
}

// ─────────────────────────────────────────────
// Kick Member (host only)
// ─────────────────────────────────────────────
export async function kickMember(hostId, roomId, targetUserId) {
  const room = await getRoomById(roomId, hostId);

  if (room.host_id !== hostId) {
    throw Object.assign(new Error('Only the host can kick members'), { code: 'FORBIDDEN', status: 403 });
  }
  if (targetUserId === hostId) {
    throw Object.assign(new Error('Cannot kick yourself'), { code: 'BAD_REQUEST', status: 400 });
  }

  const { error } = await supabaseAdmin
    .from('room_members')
    .delete()
    .eq('room_id', roomId)
    .eq('user_id', targetUserId);

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return { message: 'Member kicked successfully' };
}

// ─────────────────────────────────────────────
// Get My Rooms
// ─────────────────────────────────────────────
export async function getMyRooms(userId) {
  const { data, error } = await supabaseAdmin
    .from('room_members')
    .select(`
      role, joined_at,
      room:rooms (
        id, code, name, status, duration_mins, max_members,
        difficulty, topics, starts_at, ends_at, created_at,
        host:users!rooms_host_id_fkey (id, username, display_name, avatar_url)
      )
    `)
    .eq('user_id', userId)
    .order('joined_at', { ascending: false });

  if (error) throw Object.assign(new Error(error.message), { code: error.code, status: 400 });
  return data;
}